# -*- mode: ruby -*-
# vi: set ft=ruby :
# Vagrantfile API/syntax version. Don't touch unless you know what you're
#doing!
VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
config.vm.box = "ubuntu/trusty64"
# Begin Configuring
config.vm.define "lamp1" do|lamp1|
lamp1.vm.hostname = "lamp1" # Setting up hostname
config.vm.network :forwarded_port, guest: 80, host: 8000
lamp1.vm.provision :shell, path: "script.sh" # Provisioning with script.sh
end
end
